import fs from 'node:fs';
import path from 'node:path';
import type { ProjectAnalysis } from './walker-types';
import type { DictionaryConfig } from '../core/types';
import { resolveDictionaryOwnership } from './dictionary-ownership';
import { buildScopePlans } from './scope-bundles';

/**
 * Options for the module compiler.
 */
export interface CompilerOptions {
  /** Absolute path to the locales directory. */
  localesDir: string;
  /** List of locale codes to compile. */
  locales: string[];
  /** Default locale code used for fallback resolution. */
  defaultLocale: string;
  /** Output directory for compiled modules. */
  outDir: string;
  /** Optional dictionary configurations. */
  dictionaries?: Record<string, DictionaryConfig>;
  /**
   * Inline cross-namespace keys (tree-shaken) into each scope module.
   * See `I18nSharedConfig.bundling.crossNamespacePacking`.
   *
   * @default false
   */
  crossNamespacePacking?: boolean;
}

/**
 * Escapes backslashes and single quotes for use in JS string literals.
 */
function escapeValue(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Flattens a nested translation object into a flat Map with fully qualified keys.
 *
 * @param namespace - The namespace prefix (e.g., 'products')
 * @param data - The nested translation object
 * @param prefix - Internal prefix for recursion
 * @returns A Map of fully qualified keys to string values
 */
export function flattenNamespace(
  namespace: string,
  data: Record<string, unknown>,
  prefix?: string,
): Map<string, string> {
  const result = new Map<string, string>();
  const currentPrefix = prefix ? `${prefix}.` : `${namespace}.`;

  for (const [key, value] of Object.entries(data)) {
    const fullKey = `${currentPrefix}${key}`;
    if (typeof value === 'string') {
      result.set(fullKey, value);
    } else if (typeof value === 'object' && value !== null) {
      const nested = flattenNamespace(
        namespace,
        value as Record<string, unknown>,
        fullKey,
      );
      for (const [k, v] of nested) {
        result.set(k, v);
      }
    }
  }

  return result;
}

/**
 * Creates a new map with all keys from primary, plus any missing keys filled from fallback.
 */
export function preResolveFallbacks(
  primary: Map<string, string>,
  fallback: Map<string, string>,
): Map<string, string> {
  const result = new Map(primary);
  for (const [key, value] of fallback) {
    if (!result.has(key)) {
      result.set(key, value);
    }
  }
  return result;
}

/**
 * Generates a JavaScript module exporting a flat Map of translation entries.
 */
export function generateCompiledModule(entries: Map<string, string>): string {
  const lines: string[] = [];
  lines.push('// Auto-generated by vite-bundled-i18n. Do not edit.');
  lines.push('const m = new Map([');
  for (const [key, value] of entries) {
    lines.push(`  ['${escapeValue(key)}','${escapeValue(value)}'],`);
  }
  lines.push(']);');
  lines.push('export default m;');
  lines.push('');
  return lines.join('\n');
}

/**
 * Reads namespace JSON files for a locale and returns a combined flattened Map.
 */
function buildLocaleMap(
  localesDir: string,
  locale: string,
  namespaces: string[],
): Map<string, string> {
  const combined = new Map<string, string>();
  for (const ns of namespaces) {
    const filePath = path.join(localesDir, locale, `${ns}.json`);
    if (!fs.existsSync(filePath)) continue;
    const data = JSON.parse(
      fs.readFileSync(filePath, 'utf-8'),
    ) as Record<string, unknown>;
    const flat = flattenNamespace(ns, data);
    for (const [k, v] of flat) {
      combined.set(k, v);
    }
  }
  return combined;
}

/**
 * Reads ALL namespace JSON files for a locale directory.
 */
function buildFullLocaleMap(
  localesDir: string,
  locale: string,
): Map<string, string> {
  const localeDir = path.join(localesDir, locale);
  if (!fs.existsSync(localeDir)) return new Map();
  const files = fs.readdirSync(localeDir).filter((f) => f.endsWith('.json'));
  const namespaces = files.map((f) => f.replace(/\.json$/, ''));
  return buildLocaleMap(localesDir, locale, namespaces);
}

/**
 * Filters a map to only include entries whose keys are in the given set.
 */
function filterMap(
  map: Map<string, string>,
  keys: Set<string>,
): Map<string, string> {
  const result = new Map<string, string>();
  for (const [k, v] of map) {
    if (keys.has(k)) {
      result.set(k, v);
    }
  }
  return result;
}

/**
 * Generates a dictionary module for a locale by reading all dictionary namespace files,
 * flattening them, and pre-resolving fallbacks against the default locale.
 */
export function generateDictionaryModule(
  localesDir: string,
  locale: string,
  defaultLocale: string,
  dictionaries: Record<string, DictionaryConfig>,
  dictionaryName: string,
): string {
  const fullAvailable = buildFullLocaleMap(localesDir, defaultLocale);
  const ownership = resolveDictionaryOwnership(fullAvailable.keys(), dictionaries);
  const ownedKeys = ownership.dictionaryKeys.get(dictionaryName) ?? new Set<string>();

  const localeMap = filterMap(buildFullLocaleMap(localesDir, locale), ownedKeys);

  if (locale !== defaultLocale) {
    const defaultMap = filterMap(buildFullLocaleMap(localesDir, defaultLocale), ownedKeys);
    const resolved = preResolveFallbacks(localeMap, defaultMap);
    return generateCompiledModule(resolved);
  }

  return generateCompiledModule(localeMap);
}

/**
 * Generates a manifest module with dynamic import mappings for routes and dictionaries.
 */
export function generateManifest(
  scopeIds: string[],
  locales: string[],
  dictionaryNames: string[],
): string {
  const lines: string[] = [];
  lines.push('// Auto-generated by vite-bundled-i18n. Do not edit.');
  lines.push('export const scopes = {');
  for (const scopeId of scopeIds) {
    lines.push(`  '${escapeValue(scopeId)}': {`);
    for (const locale of locales) {
      lines.push(
        `    '${escapeValue(locale)}': () => import('./${locale}/${scopeId}.js'),`,
      );
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  lines.push('export const routes = scopes;');
  lines.push('');

  if (dictionaryNames.length > 0) {
    lines.push('export const dictionaries = {');
    for (const name of dictionaryNames) {
      lines.push(`  '${escapeValue(name)}': {`);
      for (const locale of locales) {
        lines.push(
          `    '${escapeValue(locale)}': () => import('./${locale}/_dict/${name}.js'),`,
        );
      }
      lines.push('  },');
    }
    lines.push('};');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Orchestrates the full compilation of pre-compiled i18n modules.
 */
export function compileAll(
  analysis: ProjectAnalysis,
  options: CompilerOptions,
): void {
  const { localesDir, locales, defaultLocale, outDir, dictionaries, crossNamespacePacking } = options;

  fs.mkdirSync(outDir, { recursive: true });

  // Build the default locale full map for fallback resolution
  const defaultFullMap = buildFullLocaleMap(localesDir, defaultLocale);

  // Determine which namespaces the routes reference
  const ownership = resolveDictionaryOwnership(defaultFullMap.keys(), dictionaries);

  // For each scope + locale: collect used keys, filter, resolve fallbacks, write
  const scopePlans = buildScopePlans(analysis, defaultFullMap.keys(), { crossNamespacePacking });
  for (const plan of scopePlans) {
    const usedKeys = new Set(
      [...plan.keys].filter((key) => !ownership.keyOwner.has(key)),
    );
    if (crossNamespacePacking) {
      for (const extraKeys of plan.extras.values()) {
        for (const key of extraKeys) {
          if (ownership.keyOwner.has(key)) continue;
          usedKeys.add(key);
        }
      }
    }
    for (const locale of locales) {
      const localeDir = path.join(outDir, locale);
      fs.mkdirSync(localeDir, { recursive: true });

      const localeMap = buildFullLocaleMap(localesDir, locale);
      const filtered = filterMap(localeMap, usedKeys);

      const resolved =
        locale !== defaultLocale
          ? preResolveFallbacks(filtered, filterMap(defaultFullMap, usedKeys))
          : filtered;

      const moduleSource = generateCompiledModule(resolved);
      fs.writeFileSync(
        path.join(localeDir, `${plan.scope}.js`),
        moduleSource,
      );
    }
  }

  // For each locale: generate per-dictionary modules
  if (dictionaries && Object.keys(dictionaries).length > 0) {
    for (const locale of locales) {
      const localeDir = path.join(outDir, locale);
      const dictDir = path.join(localeDir, '_dict');
      fs.mkdirSync(dictDir, { recursive: true });

      for (const dictionaryName of Object.keys(dictionaries)) {
        const dictModule = generateDictionaryModule(
          localesDir,
          locale,
          defaultLocale,
          dictionaries,
          dictionaryName,
        );
        fs.writeFileSync(path.join(dictDir, `${dictionaryName}.js`), dictModule);
      }
    }
  }

  // Generate manifest
  const scopeIds = scopePlans.map((plan) => plan.scope);
  const dictionaryNames = dictionaries ? Object.keys(dictionaries) : [];
  const manifestSource = generateManifest(scopeIds, locales, dictionaryNames);
  fs.writeFileSync(path.join(outDir, 'manifest.js'), manifestSource);
}
