// Auto-generated by vite-bundled-i18n — do not edit.
// Regenerated on: npm run dev (auto), npm run build, npm run i18n -- generate
//
// Add ".i18n" to your tsconfig include: { "include": ["src", ".i18n"] }

type TranslationValue = string | number | boolean | bigint | null | undefined;

// Direct exports — used by the package to populate types
export interface I18nNestedKeys {
    'account': {
      'addresses': {
        'addNew': true;
        'default': true;
        'heading': true;
        'setDefault': true;
      };
      'orders': {
        'empty': true;
        'heading': true;
        'orderNumber': true;
        'placedOn': true;
        'reorder': true;
        'status': {
          'cancelled': true;
          'delivered': true;
          'pending': true;
          'processing': true;
          'shipped': true;
        };
        'trackOrder': true;
      };
      'profile': {
        'changePassword': true;
        'confirmPassword': true;
        'currentPassword': true;
        'email': true;
        'heading': true;
        'name': true;
        'newPassword': true;
        'personalInfo': true;
        'phone': true;
        'updated': true;
      };
    };
    'actions': {
      'addToCart': true;
      'applyFilter': true;
      'checkout': true;
      'clearFilters': true;
      'create': true;
      'delete': true;
      'edit': true;
      'register': true;
      'removeFromCart': true;
      'save': true;
      'signIn': true;
      'signOut': true;
      'sortBy': true;
      'submit': true;
      'update': true;
      'viewDetails': true;
    };
    'cart': {
      'empty': true;
      'emptyAction': true;
      'item': {
        'moveToWishlist': true;
        'priceEach': true;
        'quantity': true;
        'remove': true;
      };
      'promoCode': {
        'applied': true;
        'apply': true;
        'invalid': true;
        'label': true;
        'placeholder': true;
      };
      'summary': {
        'estimatedDelivery': true;
        'freeShipping': true;
        'shipping': true;
        'subtotal': true;
        'tax': true;
        'total': true;
      };
      'title': true;
    };
    'global': {
      'appName': true;
      'footer': {
        'contact': true;
        'madeWith': true;
        'privacy': true;
        'terms': true;
        'version': true;
      };
      'meta': {
        'description': true;
        'title': true;
      };
      'nav': {
        'about': true;
        'account': true;
        'cart': true;
        'home': true;
        'products': true;
      };
      'tagline': true;
    };
    'products': {
      'index': {
        'empty': true;
        'filters': {
          'category': true;
          'featured': true;
          'inStock': true;
          'priceRange': true;
        };
        'heading': true;
        'sort': {
          'newest': true;
          'popular': true;
          'priceAsc': true;
          'priceDesc': true;
        };
        'subheading': true;
      };
      'reviews': {
        'averageRating': true;
        'heading': true;
        'helpful': true;
        'noReviews': true;
        'reported': true;
        'reviewCount': true;
        'writeReview': true;
      };
      'show': {
        'availability': {
          'backorder': true;
          'inStock': true;
          'outOfStock': true;
        };
        'description': true;
        'discount': true;
        'originalPrice': true;
        'price': true;
        'relatedProducts': true;
        'sku': true;
        'tabs': {
          'description': true;
          'reviews': true;
          'specifications': true;
        };
        'title': true;
      };
    };
    'shared': {
      'backToHome': true;
      'cancel': true;
      'close': true;
      'confirm': true;
      'copyright': true;
      'error': true;
      'loading': true;
      'next': true;
      'no': true;
      'noResults': true;
      'ok': true;
      'previous': true;
      'retry': true;
      'search': true;
      'yes': true;
    };
  }

export interface I18nParamsMap {
    'account.orders.orderNumber': { number: TranslationValue };
    'account.orders.placedOn': { date: TranslationValue };
    'actions.sortBy': { field: TranslationValue };
    'cart.summary.estimatedDelivery': { date: TranslationValue };
    'cart.item.quantity': { count: TranslationValue };
    'cart.item.priceEach': { amount: TranslationValue };
    'cart.promoCode.applied': { code: TranslationValue; discount: TranslationValue };
    'global.footer.madeWith': { framework: TranslationValue };
    'global.footer.version': { version: TranslationValue };
    'global.meta.title': { page: TranslationValue };
    'products.index.subheading': { count: TranslationValue };
    'products.show.price': { amount: TranslationValue };
    'products.show.originalPrice': { amount: TranslationValue };
    'products.show.discount': { percent: TranslationValue };
    'products.show.sku': { code: TranslationValue };
    'products.show.availability.inStock': { count: TranslationValue };
    'products.show.tabs.reviews': { count: TranslationValue };
    'products.reviews.averageRating': { rating: TranslationValue };
    'products.reviews.reviewCount': { count: TranslationValue };
}

export interface I18nScopeMap {
    'account': true;
    'cart': true;
    'products.index': true;
}
