import type { CompiledManifestModule } from './compiled-runtime';
import type {
  I18nNestedKeys,
  I18nParamsMap,
  I18nScopeMap,
} from 'vite-bundled-i18n/generated';

export type {
  I18nNestedKeys,
  I18nParamsMap,
  I18nScopeMap,
};

/**
 * Recursive type representing nested translation JSON.
 * Leaf values are strings (the translated text).
 * Branch values are nested objects containing more keys.
 *
 * @example
 * ```ts
 * const data: NestedTranslations = {
 *   show: {
 *     title: "Product Details",
 *     price: "Price: {{amount}}"
 *   }
 * };
 * ```
 */
export type NestedTranslations = {
  [key: string]: string | NestedTranslations;
};

/**
 * Augmentable interface for registering valid translation keys.
 *
 * When empty (no generated types), `TranslationKey` falls back to `string`,
 * so `t()` accepts any key. When the type generator populates this interface
 * via module augmentation, `t()` only accepts registered keys — enabling
 * full autocomplete and compile-time validation.
 *
 * @example
 * ```ts
 * // Generated by: npm run i18n -- generate
 * // .i18n/i18n.d.ts
 * declare module 'vite-bundled-i18n' {
 *   interface I18nNestedKeys {
 *     shared: { ok: true };
 *     products: { show: { title: true } };
 *   }
 * }
 * ```
 */
// I18nKeyMap is kept for backwards compatibility but no longer generated.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface I18nKeyMap {}

/**
 * Resolves to the union of registered scope identifiers when `I18nScopeMap`
 * has entries, or falls back to `string` when it's empty.
 */
export type ValidScope = keyof I18nScopeMap extends never
  ? string
  : keyof I18nScopeMap & string;

/**
 * Recursive dot-path expansion for nested key tree interfaces.
 * Converts `{ a: { b: true; c: { d: true } } }` to `'a.b' | 'a.c.d'`.
 *
 * Used to derive `TranslationKey` from `I18nNestedKeys` — this gives
 * progressive autocomplete in the IDE (one level at a time) instead of
 * dumping 2000+ flat strings into the completion list.
 */
export type DotPath<T, Prefix extends string = ''> = {
  [K in keyof T & string]: T[K] extends Record<string, unknown>
    ? DotPath<T[K], `${Prefix}${K}.`>
    : `${Prefix}${K}`;
}[keyof T & string];

/**
 * Resolves to the union of registered translation keys.
 *
 * When `I18nNestedKeys` is populated (by the type generator), derives
 * keys from the nested tree via `DotPath` — this gives progressive
 * autocomplete in the IDE (one segment at a time). Falls back to
 * `string` when no types are generated.
 */
export type TranslationKey = keyof I18nNestedKeys extends never
  ? string
  : DotPath<I18nNestedKeys>;

/**
 * Primitive value types accepted for interpolation placeholders.
 */
export type Primitive =
  | string
  | number
  | boolean
  | bigint
  | null
  | undefined;

/**
 * Returns the generated placeholder parameter object for a fully qualified key.
 *
 * Unknown keys fall back to a permissive record so the runtime remains usable
 * before generated types exist.
 */
export type ParamsOf<K extends TranslationKey> =
  K extends keyof I18nParamsMap
    ? I18nParamsMap[K]
    : Record<string, Primitive>;

/**
 * Translation function.
 *
 * - `t(key)` or `t(key, fallback)` — for keys without placeholders
 * - `t(key, params)` or `t(key, params, fallback)` — for keys with `{{placeholders}}`
 *
 * Params are type-checked per key: `t('cart.total', { amount: 9 })` enforces `{ amount }`.
 */
export type TFunction = {
  (key: TranslationKey): string;
  (key: TranslationKey, fallback: string): string;
  (key: TranslationKey, params: Record<string, unknown>): string;
  (key: TranslationKey, params: Record<string, unknown>, fallback: string): string;
};

/**
 * Translation function for scoped/namespace-relative keys.
 * Accepts any string since scoped keys are relative to the namespace
 * and don't match the fully qualified `TranslationKey` union.
 */
export type ScopedTFunction = {
  (key: string): string;
  (key: string, fallback: string): string;
  (key: string, params: Record<string, unknown>): string;
  (key: string, params: Record<string, unknown>, fallback: string): string;
};

/**
 * Translation function that returns undefined when the key is not currently
 * resolvable from loaded translations in the active or fallback locale.
 *
 * Unlike {@link TFunction}, this function does not accept fallback strings
 * and does not degrade to key-as-value.
 */
export type TryTFunction = {
  (key: TranslationKey): string | undefined;
  (key: TranslationKey, params: Record<string, unknown>): string | undefined;
};

/**
 * Namespace-relative version of {@link TryTFunction}.
 */
export type ScopedTryTFunction = {
  (key: string): string | undefined;
  (key: string, params: Record<string, unknown>): string | undefined;
};

/**
 * Translation function that throws when the key is not currently resolvable.
 *
 * Like {@link TryTFunction}, this function does not accept fallback strings.
 */
export type RequireTFunction = {
  (key: TranslationKey): string;
  (key: TranslationKey, params: Record<string, unknown>): string;
};

/**
 * Namespace-relative version of {@link RequireTFunction}.
 */
export type ScopedRequireTFunction = {
  (key: string): string;
  (key: string, params: Record<string, unknown>): string;
};

/**
 * Checks whether a key is currently resolvable from loaded translations in
 * either the bound locale or the configured default locale.
 */
export type HasKeyFunction = (key: string) => boolean;

/**
 * Translator object exposed by the hook, global accessors, and server helpers.
 * It normalizes translation access across React and non-React environments.
 */
export interface Translations {
  /** Short UI alias. Same behavior and identity as `get`. */
  t: TFunction;
  /** Primary lookup method for all environments. */
  get: TFunction;
  /** Returns whether the key is currently resolvable. */
  has: HasKeyFunction;
  /** Alias of `has`. */
  exists: HasKeyFunction;
  /** Returns undefined for unresolved keys instead of degrading to fallback/key. */
  tryGet: TryTFunction;
  /** Throws for unresolved keys. */
  require: RequireTFunction;
  /** Returns a translator bound to a namespace and optional key prefix. */
  namespace: (namespace: string, keyPrefix?: string) => NamespacedTranslations;
  /** Returns a translator bound to another locale. */
  forLocale: (locale: string) => Translations;
  /** Bound locale for this translator object. */
  locale: string;
}

/**
 * Namespace-bound translator object for non-qualified translation access.
 */
export interface NamespacedTranslations {
  t: ScopedTFunction;
  get: ScopedTFunction;
  has: HasKeyFunction;
  exists: HasKeyFunction;
  tryGet: ScopedTryTFunction;
  require: ScopedRequireTFunction;
  locale: string;
  namespace: string;
}

/**
 * Configuration for a named dictionary — a group of namespaces
 * that are preloaded at app initialization and available to all components.
 */
export interface DictionaryConfig {
  /**
   * Legacy namespace names (filenames without extension) to include in this
   * dictionary. Equivalent to `include: ['namespace.*']` for each entry.
   */
  keys?: string[];
  /**
   * Key ownership patterns included in this dictionary.
   * Supported patterns:
   * - `shared.*`
   * - `checkout.summary.*`
   * - `shared.ok`
   * - `admin*` (namespace prefix)
   */
  include?: string[];
  /**
   * Key patterns to exclude from this dictionary, applied after `include`.
   * Same pattern syntax as `include`. Use to carve out sub-namespaces
   * that shouldn't be preloaded (e.g., large validation keys).
   */
  exclude?: string[];
  /** Higher priority dictionaries claim matching keys first. */
  priority?: number;
  /** Whether this dictionary should be pinned in the runtime cache. */
  pinned?: boolean;
}

/**
 * Runtime in-memory caching configuration.
 */
export interface RuntimeCacheConfig {
  /** Cache strategy. */
  strategy?: 'memory' | 'none';
  /** Namespace-level eviction behavior. */
  eviction?: 'none' | 'lru';
  /** Maximum number of locales to keep in memory. */
  maxLocales?: number;
  /** Maximum number of namespaces to keep in memory. */
  maxNamespaces?: number;
  /** Approximate byte budget across all namespaces. */
  maxBytes?: number;
  /** Whether dictionary namespaces should be pinned against eviction. */
  pinDictionaries?: boolean;
}

/**
 * Cache configuration for fetch behavior and runtime memory retention.
 */
export interface CacheConfig {
  /** Runtime memory cache configuration. Legacy string values remain supported. */
  runtime?: 'memory' | 'none' | RuntimeCacheConfig;
}

export interface CacheStats {
  totalLocales: number;
  totalNamespaces: number;
  approxTotalBytes: number;
  pinnedNamespaces: number;
  loadedScopes: number;
  loadedDictionaries: number;
}

/**
 * Optional compiled-runtime configuration. When enabled, the runtime loads
 * precompiled `Map` modules instead of JSON bundles in production.
 */
export interface CompiledConfig {
  /**
   * Whether compiled mode should be attempted.
   * `auto` means "use the build-injected manifest URL when available".
   */
  enabled?: boolean | 'auto';
  /**
   * URL to the emitted compiled manifest module.
   * Defaults to the build-injected value when present.
   */
  manifestUrl?: string;
  /**
   * Custom manifest loader override. Useful for SSR, tests, or advanced runtimes.
   */
  loadManifest?: () => Promise<CompiledManifestModule>;
}

/**
 * Configuration object passed to `createI18n()`.
 */
export interface I18nConfig {
  /** Current active locale (e.g., `'en'`). */
  locale: string;
  /** Fallback locale used when a key is missing in the active locale. */
  defaultLocale: string;
  /** List of all supported locale codes. */
  supportedLocales: string[];
  /** Path to the directory containing locale folders (e.g., `'/locales'`). */
  localesDir: string;
  /**
   * Named groups of namespaces to preload at app init.
   * Keys are dictionary names, values configure which namespaces to include.
   */
  dictionaries?: Record<string, DictionaryConfig>;
  /** Caching configuration. */
  cache?: CacheConfig;
  /** Optional compiled-runtime configuration. */
  compiled?: CompiledConfig;
  /**
   * Custom options passed to every `fetch()` call made by the runtime.
   * Use this to set headers, credentials, cache mode, abort signals, etc.
   *
   * - Static object: applied as-is to every request
   * - Function: called before each request, may be async (e.g., for refreshing auth tokens)
   */
  requestInit?: RequestInit | (() => RequestInit | Promise<RequestInit>);
  /**
   * Overrides the build-injected base path for translation bundle fetches.
   * Useful for CDN or reverse proxy deployments where the runtime fetch URL
   * differs from the Vite build `base`.
   */
  publicBase?: string;
  /**
   * Custom URL resolver for all translation fetches. When provided, this
   * function controls WHERE translations are fetched from. Use alongside
   * `requestInit` which controls HOW the fetch is made (headers, credentials).
   *
   * @param locale - The locale being fetched
   * @param type - The bundle type: 'dictionary' | 'scope' | 'namespace' | 'manifest'
   * @param name - The resource name (dict name, scope id, namespace, or 'manifest')
   * @returns The URL to fetch from
   */
  resolveUrl?: (locale: string, type: 'dictionary' | 'scope' | 'namespace' | 'manifest', name: string) => string;
}

/**
 * The i18n instance returned by `createI18n()`.
 * Contains the resource store, resolved config, and methods for managing translations.
 */
export interface I18nInstance {
  /** The resolved configuration (frozen). */
  config: Readonly<I18nConfig>;

  /**
   * Resolves a fully qualified key to a translated string.
   * Handles namespace extraction, dot-path traversal, fallback chain, and interpolation.
   */
  translate: (
    locale: string,
    key: string,
    params?: Record<string, unknown>,
    fallback?: string,
  ) => string;

  /**
   * Resolves a fully qualified key without degrading to fallback strings or
   * key-as-value. Returns undefined when the key is not currently resolvable.
   */
  tryTranslate: (
    locale: string,
    key: string,
    params?: Record<string, unknown>,
  ) => string | undefined;

  /**
   * Checks if a fully qualified key exists in the store for a locale.
   */
  hasKey: (locale: string, key: string) => boolean;

  /**
   * Loads namespace JSON files for a locale via fetch and adds them to the store.
   * Skips namespaces already present in the store.
   * Prefer `loadDictionaries` and `loadScope` for bundled loading.
   */
  loadNamespaces: (locale: string, namespaces: string[]) => Promise<void>;

  /**
   * Loads a named dictionary bundle for a locale.
   * One HTTP request per dictionary: `/__i18n/{locale}/_dict/{name}.json`
   */
  loadDictionary: (locale: string, name: string) => Promise<void>;

  /**
   * Loads all configured dictionaries for a locale, in declaration order.
   * One HTTP request per dictionary name.
   */
  loadAllDictionaries: (locale: string) => Promise<void>;

  /**
   * Loads a page/scope bundle for a locale.
   * One HTTP request: `/__i18n/{locale}/{scope}.json`
   */
  loadScope: (locale: string, scope: string) => Promise<void>;

  /**
   * Adds resources directly to the store. Useful for testing and SSR.
   */
  addResources: (
    locale: string,
    namespace: string,
    data: NestedTranslations,
  ) => void;

  /** Returns one namespace's currently loaded resources, if present. */
  getResource: (
    locale: string,
    namespace: string,
  ) => NestedTranslations | undefined;

  /** Returns all currently loaded namespace names for a locale. */
  getLoadedNamespaces: (locale: string) => string[];

  /** Returns true when the namespace data is present in the store. */
  isNamespaceLoaded: (locale: string, namespace: string) => boolean;

  /** Returns true when the scope bundle has already been loaded. */
  isScopeLoaded: (locale: string, scope: string) => boolean;

  /** Returns cache and residency information for the runtime store. */
  getCacheStats: () => CacheStats;

  /** Unloads all namespaces for a locale from the runtime store. */
  unloadLocale: (locale: string) => void;

  /** Unloads a single namespace from the runtime store. */
  unloadNamespace: (locale: string, namespace: string) => void;

  /** Applies cache eviction rules immediately. */
  evictUnused: () => void;

  /**
   * Returns all unique namespace names referenced by configured dictionaries.
   */
  getDictionaryNamespaces: () => string[];

  /** Returns the current active locale. */
  getLocale: () => string;

  /**
   * Switches the active locale. Loads all dictionary namespaces and any
   * previously loaded namespaces for the new locale before notifying listeners.
   */
  changeLocale: (locale: string) => Promise<void>;

  /**
   * Subscribes to locale changes. Returns an unsubscribe function.
   */
  onLocaleChange: (callback: (locale: string) => void) => () => void;

  /**
   * Returns all key usage entries recorded since initialization.
   * Only tracks in dev mode. Useful for diagnostics, manifest generation,
   * and the dev toolbar.
   */
  getKeyUsage: () => KeyUsageEntry[];

  /**
   * Returns the dictionary names in declaration order.
   */
  getDictionaryNames: () => string[];
}

/**
 * Records how a translation key was resolved at runtime.
 * Used for dev diagnostics, manifest generation, and the dev toolbar.
 */
export interface KeyUsageEntry {
  /** The fully qualified key that was looked up. */
  key: string;
  /** The namespace extracted from the key. */
  namespace: string;
  /** The locale used for resolution. */
  locale: string;
  /** Where the value came from. */
  resolvedFrom: 'primary' | 'fallback-locale' | 'fallback-string' | 'key-as-value';
  /** The scope/bundle that triggered this lookup, if any. */
  scope?: string;
}

/**
 * Return type of the `useI18n()` hook.
 */
export interface UseI18nResult {
  /** Translation function — same signature as the global `t()`. */
  t: TFunction;
  /** Alias of `t`, preferred outside UI code. */
  get: TFunction;
  /** Returns whether the key is currently resolvable. */
  has: HasKeyFunction;
  /** Alias of `has`. */
  exists: HasKeyFunction;
  /** Returns undefined instead of fallback/key-as-value. */
  tryGet: TryTFunction;
  /** Throws when the key is not currently resolvable. */
  require: RequireTFunction;
  /** Full translator object for richer non-hook usage. */
  translations: Translations;
  /** `true` when all required translations (dictionaries + bundle) are loaded. */
  ready: boolean;
  /** The currently active locale code. */
  locale: string;
}
