// Auto-generated by vite-bundled-i18n. Do not edit.
// Run `npm run i18n -- generate` to regenerate.

// Module augmentation — wires autocomplete into t(), useI18n().t, hasKey()
declare module 'vite-bundled-i18n' {
  interface I18nKeyMap {
    'account.profile.heading': true;
    'account.profile.personalInfo': true;
    'account.profile.name': true;
    'account.profile.email': true;
    'account.profile.phone': true;
    'account.profile.changePassword': true;
    'account.profile.currentPassword': true;
    'account.profile.newPassword': true;
    'account.profile.confirmPassword': true;
    'account.profile.updated': true;
    'account.orders.heading': true;
    'account.orders.empty': true;
    'account.orders.orderNumber': true;
    'account.orders.placedOn': true;
    'account.orders.status.pending': true;
    'account.orders.status.processing': true;
    'account.orders.status.shipped': true;
    'account.orders.status.delivered': true;
    'account.orders.status.cancelled': true;
    'account.orders.trackOrder': true;
    'account.orders.reorder': true;
    'account.addresses.heading': true;
    'account.addresses.addNew': true;
    'account.addresses.setDefault': true;
    'account.addresses.default': true;
    'actions.save': true;
    'actions.delete': true;
    'actions.edit': true;
    'actions.create': true;
    'actions.update': true;
    'actions.submit': true;
    'actions.addToCart': true;
    'actions.removeFromCart': true;
    'actions.checkout': true;
    'actions.signIn': true;
    'actions.signOut': true;
    'actions.register': true;
    'actions.viewDetails': true;
    'actions.applyFilter': true;
    'actions.clearFilters': true;
    'actions.sortBy': true;
    'cart.title': true;
    'cart.empty': true;
    'cart.emptyAction': true;
    'cart.summary.subtotal': true;
    'cart.summary.shipping': true;
    'cart.summary.tax': true;
    'cart.summary.total': true;
    'cart.summary.freeShipping': true;
    'cart.summary.estimatedDelivery': true;
    'cart.item.quantity': true;
    'cart.item.remove': true;
    'cart.item.moveToWishlist': true;
    'cart.item.priceEach': true;
    'cart.promoCode.label': true;
    'cart.promoCode.placeholder': true;
    'cart.promoCode.apply': true;
    'cart.promoCode.applied': true;
    'cart.promoCode.invalid': true;
    'global.appName': true;
    'global.tagline': true;
    'global.nav.home': true;
    'global.nav.products': true;
    'global.nav.cart': true;
    'global.nav.account': true;
    'global.nav.about': true;
    'global.footer.madeWith': true;
    'global.footer.version': true;
    'global.footer.privacy': true;
    'global.footer.terms': true;
    'global.footer.contact': true;
    'global.meta.title': true;
    'global.meta.description': true;
    'products.index.heading': true;
    'products.index.subheading': true;
    'products.index.empty': true;
    'products.index.filters.category': true;
    'products.index.filters.priceRange': true;
    'products.index.filters.inStock': true;
    'products.index.filters.featured': true;
    'products.index.sort.newest': true;
    'products.index.sort.priceAsc': true;
    'products.index.sort.priceDesc': true;
    'products.index.sort.popular': true;
    'products.show.title': true;
    'products.show.description': true;
    'products.show.price': true;
    'products.show.originalPrice': true;
    'products.show.discount': true;
    'products.show.sku': true;
    'products.show.availability.inStock': true;
    'products.show.availability.outOfStock': true;
    'products.show.availability.backorder': true;
    'products.show.tabs.description': true;
    'products.show.tabs.specifications': true;
    'products.show.tabs.reviews': true;
    'products.show.relatedProducts': true;
    'products.reviews.heading': true;
    'products.reviews.writeReview': true;
    'products.reviews.averageRating': true;
    'products.reviews.reviewCount': true;
    'products.reviews.noReviews': true;
    'products.reviews.helpful': true;
    'products.reviews.reported': true;
    'shared.ok': true;
    'shared.cancel': true;
    'shared.next': true;
    'shared.previous': true;
    'shared.copyright': true;
    'shared.loading': true;
    'shared.error': true;
    'shared.retry': true;
    'shared.close': true;
    'shared.confirm': true;
    'shared.yes': true;
    'shared.no': true;
    'shared.search': true;
    'shared.noResults': true;
    'shared.backToHome': true;
  }

  interface I18nParamsMap {
    'account.profile.heading': {};
    'account.profile.personalInfo': {};
    'account.profile.name': {};
    'account.profile.email': {};
    'account.profile.phone': {};
    'account.profile.changePassword': {};
    'account.profile.currentPassword': {};
    'account.profile.newPassword': {};
    'account.profile.confirmPassword': {};
    'account.profile.updated': {};
    'account.orders.heading': {};
    'account.orders.empty': {};
    'account.orders.orderNumber': { number: Primitive };
    'account.orders.placedOn': { date: Primitive };
    'account.orders.status.pending': {};
    'account.orders.status.processing': {};
    'account.orders.status.shipped': {};
    'account.orders.status.delivered': {};
    'account.orders.status.cancelled': {};
    'account.orders.trackOrder': {};
    'account.orders.reorder': {};
    'account.addresses.heading': {};
    'account.addresses.addNew': {};
    'account.addresses.setDefault': {};
    'account.addresses.default': {};
    'actions.save': {};
    'actions.delete': {};
    'actions.edit': {};
    'actions.create': {};
    'actions.update': {};
    'actions.submit': {};
    'actions.addToCart': {};
    'actions.removeFromCart': {};
    'actions.checkout': {};
    'actions.signIn': {};
    'actions.signOut': {};
    'actions.register': {};
    'actions.viewDetails': {};
    'actions.applyFilter': {};
    'actions.clearFilters': {};
    'actions.sortBy': { field: Primitive };
    'cart.title': {};
    'cart.empty': {};
    'cart.emptyAction': {};
    'cart.summary.subtotal': {};
    'cart.summary.shipping': {};
    'cart.summary.tax': {};
    'cart.summary.total': {};
    'cart.summary.freeShipping': {};
    'cart.summary.estimatedDelivery': { date: Primitive };
    'cart.item.quantity': { count: Primitive };
    'cart.item.remove': {};
    'cart.item.moveToWishlist': {};
    'cart.item.priceEach': { amount: Primitive };
    'cart.promoCode.label': {};
    'cart.promoCode.placeholder': {};
    'cart.promoCode.apply': {};
    'cart.promoCode.applied': { code: Primitive; discount: Primitive };
    'cart.promoCode.invalid': {};
    'global.appName': {};
    'global.tagline': {};
    'global.nav.home': {};
    'global.nav.products': {};
    'global.nav.cart': {};
    'global.nav.account': {};
    'global.nav.about': {};
    'global.footer.madeWith': { framework: Primitive };
    'global.footer.version': { version: Primitive };
    'global.footer.privacy': {};
    'global.footer.terms': {};
    'global.footer.contact': {};
    'global.meta.title': { page: Primitive };
    'global.meta.description': {};
    'products.index.heading': {};
    'products.index.subheading': { count: Primitive };
    'products.index.empty': {};
    'products.index.filters.category': {};
    'products.index.filters.priceRange': {};
    'products.index.filters.inStock': {};
    'products.index.filters.featured': {};
    'products.index.sort.newest': {};
    'products.index.sort.priceAsc': {};
    'products.index.sort.priceDesc': {};
    'products.index.sort.popular': {};
    'products.show.title': {};
    'products.show.description': {};
    'products.show.price': { amount: Primitive };
    'products.show.originalPrice': { amount: Primitive };
    'products.show.discount': { percent: Primitive };
    'products.show.sku': { code: Primitive };
    'products.show.availability.inStock': { count: Primitive };
    'products.show.availability.outOfStock': {};
    'products.show.availability.backorder': {};
    'products.show.tabs.description': {};
    'products.show.tabs.specifications': {};
    'products.show.tabs.reviews': { count: Primitive };
    'products.show.relatedProducts': {};
    'products.reviews.heading': {};
    'products.reviews.writeReview': {};
    'products.reviews.averageRating': { rating: Primitive };
    'products.reviews.reviewCount': { count: Primitive };
    'products.reviews.noReviews': {};
    'products.reviews.helpful': {};
    'products.reviews.reported': {};
    'shared.ok': {};
    'shared.cancel': {};
    'shared.next': {};
    'shared.previous': {};
    'shared.copyright': {};
    'shared.loading': {};
    'shared.error': {};
    'shared.retry': {};
    'shared.close': {};
    'shared.confirm': {};
    'shared.yes': {};
    'shared.no': {};
    'shared.search': {};
    'shared.noResults': {};
    'shared.backToHome': {};
  }
}

/** Union of all valid translation key paths. */
export type TranslationKey =
  | 'account.profile.heading'
  | 'account.profile.personalInfo'
  | 'account.profile.name'
  | 'account.profile.email'
  | 'account.profile.phone'
  | 'account.profile.changePassword'
  | 'account.profile.currentPassword'
  | 'account.profile.newPassword'
  | 'account.profile.confirmPassword'
  | 'account.profile.updated'
  | 'account.orders.heading'
  | 'account.orders.empty'
  | 'account.orders.orderNumber'
  | 'account.orders.placedOn'
  | 'account.orders.status.pending'
  | 'account.orders.status.processing'
  | 'account.orders.status.shipped'
  | 'account.orders.status.delivered'
  | 'account.orders.status.cancelled'
  | 'account.orders.trackOrder'
  | 'account.orders.reorder'
  | 'account.addresses.heading'
  | 'account.addresses.addNew'
  | 'account.addresses.setDefault'
  | 'account.addresses.default'
  | 'actions.save'
  | 'actions.delete'
  | 'actions.edit'
  | 'actions.create'
  | 'actions.update'
  | 'actions.submit'
  | 'actions.addToCart'
  | 'actions.removeFromCart'
  | 'actions.checkout'
  | 'actions.signIn'
  | 'actions.signOut'
  | 'actions.register'
  | 'actions.viewDetails'
  | 'actions.applyFilter'
  | 'actions.clearFilters'
  | 'actions.sortBy'
  | 'cart.title'
  | 'cart.empty'
  | 'cart.emptyAction'
  | 'cart.summary.subtotal'
  | 'cart.summary.shipping'
  | 'cart.summary.tax'
  | 'cart.summary.total'
  | 'cart.summary.freeShipping'
  | 'cart.summary.estimatedDelivery'
  | 'cart.item.quantity'
  | 'cart.item.remove'
  | 'cart.item.moveToWishlist'
  | 'cart.item.priceEach'
  | 'cart.promoCode.label'
  | 'cart.promoCode.placeholder'
  | 'cart.promoCode.apply'
  | 'cart.promoCode.applied'
  | 'cart.promoCode.invalid'
  | 'global.appName'
  | 'global.tagline'
  | 'global.nav.home'
  | 'global.nav.products'
  | 'global.nav.cart'
  | 'global.nav.account'
  | 'global.nav.about'
  | 'global.footer.madeWith'
  | 'global.footer.version'
  | 'global.footer.privacy'
  | 'global.footer.terms'
  | 'global.footer.contact'
  | 'global.meta.title'
  | 'global.meta.description'
  | 'products.index.heading'
  | 'products.index.subheading'
  | 'products.index.empty'
  | 'products.index.filters.category'
  | 'products.index.filters.priceRange'
  | 'products.index.filters.inStock'
  | 'products.index.filters.featured'
  | 'products.index.sort.newest'
  | 'products.index.sort.priceAsc'
  | 'products.index.sort.priceDesc'
  | 'products.index.sort.popular'
  | 'products.show.title'
  | 'products.show.description'
  | 'products.show.price'
  | 'products.show.originalPrice'
  | 'products.show.discount'
  | 'products.show.sku'
  | 'products.show.availability.inStock'
  | 'products.show.availability.outOfStock'
  | 'products.show.availability.backorder'
  | 'products.show.tabs.description'
  | 'products.show.tabs.specifications'
  | 'products.show.tabs.reviews'
  | 'products.show.relatedProducts'
  | 'products.reviews.heading'
  | 'products.reviews.writeReview'
  | 'products.reviews.averageRating'
  | 'products.reviews.reviewCount'
  | 'products.reviews.noReviews'
  | 'products.reviews.helpful'
  | 'products.reviews.reported'
  | 'shared.ok'
  | 'shared.cancel'
  | 'shared.next'
  | 'shared.previous'
  | 'shared.copyright'
  | 'shared.loading'
  | 'shared.error'
  | 'shared.retry'
  | 'shared.close'
  | 'shared.confirm'
  | 'shared.yes'
  | 'shared.no'
  | 'shared.search'
  | 'shared.noResults'
  | 'shared.backToHome';

/** Union of all namespace names. */
export type Namespace = 'account' | 'actions' | 'cart' | 'global' | 'products' | 'shared';

/** Key paths within a specific namespace (without the namespace prefix). */
export type NamespaceKeyPaths<T extends Namespace> =
  T extends 'account' ? 'profile.heading' | 'profile.personalInfo' | 'profile.name' | 'profile.email' | 'profile.phone' | 'profile.changePassword' | 'profile.currentPassword' | 'profile.newPassword' | 'profile.confirmPassword' | 'profile.updated' | 'orders.heading' | 'orders.empty' | 'orders.orderNumber' | 'orders.placedOn' | 'orders.status.pending' | 'orders.status.processing' | 'orders.status.shipped' | 'orders.status.delivered' | 'orders.status.cancelled' | 'orders.trackOrder' | 'orders.reorder' | 'addresses.heading' | 'addresses.addNew' | 'addresses.setDefault' | 'addresses.default' :
  T extends 'actions' ? 'save' | 'delete' | 'edit' | 'create' | 'update' | 'submit' | 'addToCart' | 'removeFromCart' | 'checkout' | 'signIn' | 'signOut' | 'register' | 'viewDetails' | 'applyFilter' | 'clearFilters' | 'sortBy' :
  T extends 'cart' ? 'title' | 'empty' | 'emptyAction' | 'summary.subtotal' | 'summary.shipping' | 'summary.tax' | 'summary.total' | 'summary.freeShipping' | 'summary.estimatedDelivery' | 'item.quantity' | 'item.remove' | 'item.moveToWishlist' | 'item.priceEach' | 'promoCode.label' | 'promoCode.placeholder' | 'promoCode.apply' | 'promoCode.applied' | 'promoCode.invalid' :
  T extends 'global' ? 'appName' | 'tagline' | 'nav.home' | 'nav.products' | 'nav.cart' | 'nav.account' | 'nav.about' | 'footer.madeWith' | 'footer.version' | 'footer.privacy' | 'footer.terms' | 'footer.contact' | 'meta.title' | 'meta.description' :
  T extends 'products' ? 'index.heading' | 'index.subheading' | 'index.empty' | 'index.filters.category' | 'index.filters.priceRange' | 'index.filters.inStock' | 'index.filters.featured' | 'index.sort.newest' | 'index.sort.priceAsc' | 'index.sort.priceDesc' | 'index.sort.popular' | 'show.title' | 'show.description' | 'show.price' | 'show.originalPrice' | 'show.discount' | 'show.sku' | 'show.availability.inStock' | 'show.availability.outOfStock' | 'show.availability.backorder' | 'show.tabs.description' | 'show.tabs.specifications' | 'show.tabs.reviews' | 'show.relatedProducts' | 'reviews.heading' | 'reviews.writeReview' | 'reviews.averageRating' | 'reviews.reviewCount' | 'reviews.noReviews' | 'reviews.helpful' | 'reviews.reported' :
  T extends 'shared' ? 'ok' | 'cancel' | 'next' | 'previous' | 'copyright' | 'loading' | 'error' | 'retry' | 'close' | 'confirm' | 'yes' | 'no' | 'search' | 'noResults' | 'backToHome' :
  never;
